# Copyright (c) 2024 Smart Rollerz e.V.
# All rights reserved.

path_planning_node:
  ros__parameters:
    # subscriber
    lane_points_subscriber: '/lane_detection/lane'
    image_subscriber: '/lane_detection/debug/image'
    remote_state_subscriber: '/remoteState' # Todo update
    targetSteeringAngle_pub: '/control/steering_angle/target'
    pose_estimation_subscriber: '/pose_estimation/pose'
    new_image_subscriber: '/lane_detection/new_image'


    # publisher
    image_debug_publisher: '/path_planning/debug/image'
    path_planning_right_publisher: '/path_planning/target/right'
    path_planning_left_publisher: '/path_planning/target/left'
    ref_point_publisher: '/path_planning/target/pose'         # maybe change to pathplanning

    # additional params
    trj_look_forward: 100      # adapt to speed and runtime
    state: 1 # TODO: Change to 0
